# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 523cdf6bb3cf1cad77b5562d239b3caab562cfb3bb6245bdb36ee67c42238e277b0dcf1977e8a3039a66cd5799e063ba059a6c8e389c4194c65182835b8462b9

test:
  secret_key_base: 5213294c04ff0073760975866611875c8225a5044cb1c7705d8d7c3692f12db44ee792f8b565f6a73d6f16d75aa216a65e8196c5dde79b566c70479eea3afe7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
